# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/recyclarr/recyclarr/wiki/Configuration-Reference

# Configuration specific to Radarr.
radarr:
  # Set the URL/API Key to your actual instance
  unlimited_radarr:
    base_url: http://unlimited_radarr:7878
    api_key: arr_api_key  
       
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Media Naming Configuration
    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb

    # Quality Definition Configuration
    quality_definition:
      type: movie

    quality_profiles:
      - name: 1080p
        min_format_score: 20000
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray|WEB-1080p
          until_score: 25000
        score_set: default
        quality_sort: top
        qualities:
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBDL-1080p
          - name: Bluray|WEB-720p
            qualities:
              - WEBDL-720p
              - Bluray-720p
          - name: Bluray|WEB-480p
            qualities:
              - Bluray-576p
              - Bluray-480p
              - WEBDL-480p
          - name: DVD

      - name: 2160p
        min_format_score: 20000
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray|WEB-2160p
          until_score: 25000
        score_set: default
        quality_sort: top
        qualities:
          - name: Bluray|WEB-2160p
            qualities:
              - Bluray-2160p
              - WEBDL-2160p
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBDL-1080p
          - name: Bluray|WEB-720p
            qualities:
              - WEBDL-720p
              - Bluray-720p
          - name: Bluray|WEB-480p
            qualities:
              - Bluray-576p
              - Bluray-480p
              - WEBDL-480p
          - name: DVD

      - name: 2160p Only
        min_format_score: 20000
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray|WEB-2160p
          until_score: 25000
        score_set: default
        quality_sort: top
        qualities:
          - name: Bluray|WEB-2160p
            qualities:
              - Bluray-2160p
              - WEBDL-2160p

    custom_formats:           
      - trash_ids:
        # [No Category]
        - e098247bc6652dd88c76644b275260ed # FLUX
        - 8df7fe4569063d39319f07e69707285a # WEBDL Boost
        - 2051402ee9ca81162017d98cbe1dff2c # Wrong Language
        - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hallowed
        # Audio Channels
        - b124be9b146540f8e62f98fe32e49a2a # 1.0 Mono
        - 89dac1be53d5268a7e10a19d3c896826 # 2.0 Stereo
        - 205125755c411c3b8622ca3175d27b37 # 3.0 Sound
        - 373b58bd188fc00c817bd8c7470ea285 # 4.0 Sound
        - 77ff61788dfe1097194fd8743d7b4524 # 5.1 Surround
        - 6fd7b090c3f7317502ab3b63cc7f51e3 # 6.1 Surround
        - e77382bcfeba57cb83744c9c5449b401 # 7.1 Surround
        # Audio Formats
        - c2998bd0d90ed5621d8df281e839436e # DD
        - 185f1dd7264c4562b9022d963ac37424 # DD+
        - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
        # HDR Formats
        - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
        - 493b6d1dbec3c3364c59d7607f7e3405 # HDR
        - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost
        # HDR Optional
        - f700d29429c023a5734505e77daeaea7 # DV (Disk)
        - 923b6abef9b17f937fab56cfcf89e1f1 # DV (w/o HDR fallback)
        - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        # HQ Release Groups
        - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
        - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
        - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
        - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
        - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
        - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
        - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
        - a58f517a70193f8e578056642178419d # UHD Bluray Tier 02
        - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
        - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
        - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
        - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        # Language profiles
        - d6e9318c875905d6cfb5bee961afcea9 # Language: Not Original        
        # Miscellaneous
        - 820b09bb9acbfde9c35c71e0e565dad8 # 1080p
        - fb392fb0d61a010ae38e49ceaa24a1ef # 2160p
        - b2be17d608fc88818940cd1833b0b24c # 720p
        - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
        - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
        - 9de657fd3d327ecf144ec73dfe3a3e9a # Dutch Groups
        - 0d91270a7255a1e388fa85e959f359d8 # FreeLeech
        - 73613461ac2cea99d52c4cd6e177ab82 # HFR
        - 182fa1c42a2468f8488e6dcf75a81b81 # INTERNAL
        - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
        - ae43b294509409a6a13919dedd4764c4 # Repack2
        - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3
        # Movie Versions
        - 0f12c086e289cf966fa5948eac571f44 # Hybrid
        - eecf3a857724171f968a66cb5719e152 # IMAX
        - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
        # Streaming Services
        - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
        - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
        - 2a6039655313bf5dab1e43523b62c374 # MA
        - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
        - 40e9380490e748672c2522eaaeb692f7 # ATVP
        - 84272245b2988854bfb76a16e60baea5 # DSNP
        - 509e5f41146e278f9eab1ddaceb34515 # HBO
        - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
        - 526d445d4c16214309f0fd2b3be18a89 # Hulu
        - e0ec9672be6cac914ffad34a6b077209 # iT
        - 6a061313d22e51e0f25b7cd4dc065233 # MAX
        - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
        - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
        - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
        - c2863d2a50c9acad1fb50e53ece60817 # STAN
        # Unwanted
        - ed38b889b31be83fda192888e2286d83 # BR-DISK
        - e6886871085226c3da1830830146846c # Generated Dynamic HDR
        - 90a6f9a284dff5103f6346090e6280c8 # LQ
        - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
        - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
        - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
        - 0a3f082873eb454bde444150b70253cc # Extras
        - 712d74cd88bceb883ee32f773656b1f5 # Sing-Along Versions
        - a5d148168c4506b55cf53984107c396e # Hi10P
        - cae4ca30163749b891686f95532519bd # AV1
        - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: 1080p
          - name: 2160p
          - name: 2160p Only

      - trash_ids:
        # Miscellaneous
        - 9170d55c319f4fe40da8711ba9d8050d # x265
        - 2899d84dc9372de3408e6d8cc18e9666 # x264
        assign_scores_to:
          - name: 1080p
            score: 20000
          - name: 2160p
            score: 20000
          - name: 2160p Only
            score: 20000

      - trash_ids:
        # [No Category]
        - 8df7fe4569063d39319f07e69707285a # WEBDL Boost
        # Audio Channels
        - 77ff61788dfe1097194fd8743d7b4524 # 5.1 Surround
        - 6fd7b090c3f7317502ab3b63cc7f51e3 # 6.1 Surround
        - e77382bcfeba57cb83744c9c5449b401 # 7.1 Surround
        # Audio Formats
        - a061e2e700f81932daf888599f8a8273 # Opus
        # Language profiles
        - 533f782474f0819643c2ec0c1eeeb0ac # Language: Not French
        - 0542a48746585dc4444bbbb8a6bdf6ea # Language: Original + French
        - 4eadb75fb23d09dfc0a8e3f687e72287 # Not German or English
        assign_scores_to:
          - name: 1080p
            score: 10
          - name: 2160p
            score: 10
          - name: 2160p Only
            score: 10
            
      - trash_ids:
        # Audio Channels
        - b124be9b146540f8e62f98fe32e49a2a # 1.0 Mono
        - 89dac1be53d5268a7e10a19d3c896826 # 2.0 Stereo
        - 205125755c411c3b8622ca3175d27b37 # 3.0 Sound
        - 373b58bd188fc00c817bd8c7470ea285 # 4.0 Sound
        # Audio Formats
        - 240770601cc226190c367ef59aba7463 # AAC
        assign_scores_to:
          - name: 1080p
            score: 5
          - name: 2160p
            score: 5
          - name: 2160p Only
            score: 5
            
      - trash_ids:
        # Language profiles
        - 86bc3115eb4e9873ac96904a4a68e19e # German
        - f845be10da4f442654c13e1f2c3d6cd5 # German DL
        - 6aad77771dabe9d3e9d7be86f310b867 # German DL (undefined)
        - 0dc8aec3bd1c47cd6c40c46ecd27e846 # Language: Not English        
        # Movie Versions
        - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
        - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
        - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
        - 09d9dd29a0fc958f9796e65c2a8864b4 # Open Matte
        - 570bc9ebecd92723d2d21500f4be314c # Remaster
        - 957d0f44b592285f26449575e8b1167e # Special Edition
        - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
        # Miscellaneous
        - 4b900e171accbfb172729b63323ea8ca # MULTi
        - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
        - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
        - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
        - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: 1080p
            score: -10
          - name: 2160p
            score: -10
          - name: 2160p Only
            score: -10
