# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/recyclarr/recyclarr/wiki/Configuration-Reference

# Configuration specific to Radarr.
radarr:
  # Set the URL/API Key to your actual instance
  unlimited_radarr:
    base_url: http://unlimited_radarr:7878
    api_key: arr_api_key  
       
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Media Naming Configuration
    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb

    # Include Configuration
    include:
      # Quality Definitions
      - template: radarr-quality-definition-sqp-streaming

      # sqp-1-web-1080p
      - template: radarr-quality-profile-sqp-1-web-1080p
      - template: radarr-custom-formats-sqp-1-web-1080p

      # sqp-1-web-2160p
      - template: radarr-custom-formats-sqp-1-web-2160p
      - template: radarr-quality-profile-sqp-1-web-2160p
      # - template: radarr-quality-profile-sqp-1-web-2160p-4k-only

      # anime
      #- template: radarr-quality-definition-anime
      #- template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    quality_profiles:
      - name: 1080p
        # Uncomment the below line if you don't have access to top-tier indexers
        min_format_score: 20000
        upgrade:
          allowed: true
          until_score: 25000
        qualities:
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBDL-1080p
          - name: Bluray|WEB-720p
            qualities:
              - WEBDL-720p
              - Bluray-720p
          - name: Bluray|WEB-480p
            qualities:
              - Bluray-576p
              - Bluray-480p
              - WEBDL-480p
          - name: DVD
          
      - name: SQP-1 WEB (1080p)
        # Uncomment the below line if you don't have access to top-tier indexers
        min_format_score: 10
        upgrade:
          allowed: true
          until_score: 15000
        qualities:
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBDL-1080p
          - name: Bluray|WEB-720p
            qualities:
              - WEBDL-720p
              - Bluray-720p
          - name: Bluray|WEB-480p
            qualities:
              - Bluray-576p
              - Bluray-480p
              - WEBDL-480p
          - name: DVD

      - name: SQP-1 WEB (2160p)
        min_format_score: 10
        qualities:
          - name: Bluray|WEB-2160p
            qualities:
              - Bluray-2160p
              - WEBDL-2160p
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBDL-1080p
          - name: Bluray|WEB-720p
            qualities:
              - WEBDL-720p
              - Bluray-720p
          - name: Bluray|WEB-480p
            qualities:
              - Bluray-576p
              - Bluray-480p
              - WEBDL-480p
          - name: DVD

      - name: Remux-1080p - Anime
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEBDL-1080p
          until_score: 10000
        min_format_score: 100
        score_set: anime-radarr
        quality_sort: top
        qualities:
          - name: WEBDL-1080p
          - name: RIP-1080p
            qualities:
              - Bluray-1080p
              - WEBRip-1080p
              - HDTV-1080p
          - name: Remux-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
              - HDTV-720p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV

    custom_formats:
      - trash_ids:
        # Miscellaneous
        - 2899d84dc9372de3408e6d8cc18e9666 # x264
        - 9170d55c319f4fe40da8711ba9d8050d # x265
        assign_scores_to:
          - name: 1080p
            score: 20000
            
      - trash_ids:
        # [No Category]
        - 9681750c690210f0936faed781bb7f06 # 126811
        - e098247bc6652dd88c76644b275260ed # FLUX
        - 2051402ee9ca81162017d98cbe1dff2c # Wrong Language
        # Audio Formats
        - c2998bd0d90ed5621d8df281e839436e # DD
        - 185f1dd7264c4562b9022d963ac37424 # DD+
        - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
        # HDR Optional
        - 923b6abef9b17f937fab56cfcf89e1f1 # DV (w/o HDR fallback)
        # Miscellaneous
        - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
        - ae43b294509409a6a13919dedd4764c4 # Repack2
        - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3
        assign_scores_to:
          - name: 1080p


    
      - trash_ids:
        # Movie Versions
        # Uncomment any of the next six lines to prefer these movie versions
          - eecf3a857724171f968a66cb5719e152 # IMAX
        # Uncomment the next line if you prefer WEBDL with IMAX Enhanced to BHDStudio
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

        # Optional - uncomment any of the following if you want them added to your profile
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene

        # Language profiles
          - d6e9318c875905d6cfb5bee961afcea9 # Language: Not Original

        # [No Category]
          - 2051402ee9ca81162017d98cbe1dff2c # Wrong Language
        assign_scores_to:
          - name: SQP-1 WEB (1080p)
          - name: SQP-1 WEB (2160p)

      # Unwanted
      - trash_ids:
        # Language profiles
          - 0dc8aec3bd1c47cd6c40c46ecd27e846 # Language: Not English
        # Miscellaneous
          - 4b900e171accbfb172729b63323ea8ca # MULTi
        assign_scores_to:
          - name: SQP-1 WEB (1080p)
            score: -10
          - name: SQP-1 WEB (2160p)
            score: -10 

      # Unwanted
      - trash_ids:
        # Movie Versions
          - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
        # [No Category]
          - 8df7fe4569063d39319f07e69707285a # WEBDL Boost
        assign_scores_to:
          - name: SQP-1 WEB (1080p)
            score: 25
          - name: SQP-1 WEB (2160p)
            score: 25     

      # Optional
      - trash_ids:
          # HDR10+ Boost - Uncomment the HDR10+ Boost line if you want to prefer HDR10+ releases
          # DV Boost - Uncomment the DV Boost line if you want to prefer DV releases
          # Uncomment both lines if you want to prefer both (DV HDR10+)
          - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
          - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost

        # Optional SDR
          # Only ever use ONE of the following custom formats:
          # SDR - block ALL SDR releases
          # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
          #- 9c38ebb7384dada637be8899efa68e6f # SDR
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: SQP-1 WEB (2160p)

      # Remux-1080p - Anime
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 25 # Adjust scoring as desired

      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10 # Adjust scoring as desired

      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 25 # Adjust scoring as desired
