# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/recyclarr/recyclarr/wiki/Configuration-Reference

# Configuration specific to Radarr.
radarr:
  # Set the URL/API Key to your actual instance
  unlimited_radarr:
    base_url: http://unlimited_radarr:7878
    api_key: arr_api_key  
       
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Media Naming Configuration
    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb
