sonarr:
  unlimited_sonarr:
    base_url: http://unlimited_sonarr:8989
    api_key: arr_api_key
            
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Media Naming Configuration
    media_naming:
      series: plex-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      
    quality_profiles:
      - name: 1080p
        min_format_score: 20000
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEBDL-1080p
          until_score: 25000
        score_set: default
        quality_sort: top
        qualities:
          - name: WEBDL-1080p
          - name: Bluray-1080p
          - name: WEBRip-1080p
          - name: WEBDL-720p
          - name: Bluray-720p
          - name: WEBRip-720p
          - name: WEBDL-480p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEBRip-480p
          - name: DVD
          - name: SDTV

      - name: 2160p
        min_format_score: 20000
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEBDL-2160p
          until_score: 25000
        score_set: default
        quality_sort: top
        qualities:
          - name: WEBDL-2160p
          - name: Bluray-2160p
          - name: WEBRip-2160p
          - name: WEBDL-1080p
          - name: Bluray-1080p
          - name: WEBRip-1080p
          - name: WEBDL-720p
          - name: Bluray-720p
          - name: WEBRip-720p
          - name: WEBDL-480p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEBRip-480p
          - name: DVD
          - name: SDTV

      - name: 2160p Only
        min_format_score: 20000
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEBDL-2160p
          until_score: 25000
        score_set: default
        quality_sort: top
        qualities:
          - name: WEBDL-2160p
          - name: Bluray-2160p
          - name: WEBRip-2160p

    custom_formats:
      - trash_ids:
        # [No Category]
          - 5d9fd1b1e06cd8a475462f40214b7df6 # FLUX
          - 4a20cfb76b5f92a8ca22b894b32e71be # Multi-Episode

        # Audio Channels
          - bd6dd5e043aa27ff4696a08d011c7d96 # 1.0 Mono
          - 834e534f103938853ffced4203b53e72 # 2.0 Stereo
          - 42cba7e38c7947a6d1d0a62580ee6d62 # 3.0 Sound
          - 1895195e84767de180653914ce207245 # 4.0 Sound
          - 3fbafa924f361e66fbc6187af82dfa85 # 5.1 Surround
          - 9fb6d778592c293467437593ef394bf1 # 6.1 Surround
          - 204c8c3e7315bb0ea81332774fa888d6 # 7.1 Surround

        # Audio Formats
          - dbe00161b08a25ac6154c55f95e6318d # DD
          - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS

        # General Streaming Services
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - d9e511921c8cedc7282e291b0209cdc5 # ATV
          - f67c9ca88f463a48346062e8ad07713f # ATVP
          - 77a7b25585c18af08f60b1547bb9b4fb # CC
          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
          - a880d6abc21e7c16884f3ae393f84179 # HMAX
          - f6cce30f1733d5c8194222a7507909bb # HULU
          - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
          - d34870697c9db575f17700212167be23 # NF
          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
          - 6eb71887a8db6e783dd398446eb0e65d # PLAY
          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
          - da393fd4e2c0cce7c9dc2669c43e0593 # ROKU
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213 # STAN
          - 9623c5c9cac8e939c1b9aedd32f640bf # SYFY
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
          
        # HDR Formats
          - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
          - 505d871304820ba7106b693be6fe4a9e # HDR
          - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost

        # HDR Optional
          - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)

        # HQ Source Groups
          - d6819cba26b1a6508138d25fb5e32293 # HD Bluray Tier 01
          - c2216b7b8aa545dc1ce8388c618f8d57 # HD Bluray Tier 02
          - 9965a052eb87b0d10313b1cea89eb451 # Remux Tier 01
          - 8a1d0c3d7497e741736761a1da866a2e # Remux Tier 02
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03

        # Language profiles
          - ae575f95ab639ba5d15f663bf019e3e8 # Language: Not Original

        # Miscellaneous
          - 290078c8b266272a5cc8e251b5e2eb0b # 1080p
          - 1bef6c151fa35093015b0bfef18279e5 # 2160p
          - c99279ee27a154c2f20d1d505cc99e25 # 720p
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - d7c747094a7c65f4c2de083c24899e8b # FreeLeech
          - 1bd69272e23c5e6c5b1d6c8a36fce95e # HFR
          - 5ab46ff851b76c337e13e81a4353875f # INTERNAL
          - 4aee45b0868229c4fbd8bad3e315f1d0 # MPEG2
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack2
          - 44e7c4de10ae50265753082e5dc76047 # Repack3
          - 7470a681e6205243983c4410ee4c920f # VC-1
          - 90501962793d580d011511155c97e4e5 # VP9
          - cddfb4e32db826151d97352b8e37c648 # x264
          - c9eafd50846d299b862ca9bb6ea91950 # x265
          - 041d90b435ebd773271cea047a457a6a # x266

        # Optional Streaming Services
          - 218e93e5702f44a68ad9e3c6ba87d2f0 # HD Streaming Boost
          - 43b3cf48cb385cd3eac608ee6bca7f09 # UHD Streaming Boost

        # Series Versions
          - 3a4127d8aa781b44120d907f2cd62627 # Hybrid
          - b735f09d3c025cbb7d75a5d38325b73b # Remaster
          
        # Unwanted
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled
        assign_scores_to:
          - name: 1080p
          - name: 2160p
          - name: 2160p Only

      - trash_ids:
        # Miscellaneous
          - c9eafd50846d299b862ca9bb6ea91950 # x265
        assign_scores_to:
          - name: 1080p
            score: 20005
          - name: 2160p
            score: 20005
          - name: 2160p Only
            score: 20005

      - trash_ids:
        # Miscellaneous
          - cddfb4e32db826151d97352b8e37c648 # x264
        assign_scores_to:
          - name: 1080p
            score: 20000
          - name: 2160p
            score: 20000
          - name: 2160p Only
            score: 20000

      - trash_ids:
        # Audio Channels
          - 3fbafa924f361e66fbc6187af82dfa85 # 5.1 Surround
          - 9fb6d778592c293467437593ef394bf1 # 6.1 Surround
          - 204c8c3e7315bb0ea81332774fa888d6 # 7.1 Surround
        # Miscellaneous
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
        # Audio Formats
          - 28f6ef16d61e2d1adfce3156ed8257e3 # Opus
         # Language profiles
          - 8a9fcdbb445f2add0505926df3bb7b8a # German
          - ed51973a811f51985f14e2f6f290e47a # German DL
          - c5dd0fd675f85487ad5bdf97159180bd # German DL (undefined)
          - 322fca6f8f3694acc1401ddb530fd33d # Language: Not French
          - 10e77b96ae4770a7de645a91a53ce29a # Language: Original + French
          - 133589380b89f8f8394320901529bac1 # Not German or English
        assign_scores_to:
          - name: 1080p
            score: 10
          - name: 2160p
            score: 10
          - name: 2160p Only
            score: 10

      - trash_ids:
        # [No Category]
          - e0c1a67f23908a55b6ae9834e8ed6727 # Single Episode
        # Audio Channels
          - bd6dd5e043aa27ff4696a08d011c7d96 # 1.0 Mono
          - 834e534f103938853ffced4203b53e72 # 2.0 Stereo
          - 42cba7e38c7947a6d1d0a62580ee6d62 # 3.0 Sound
          - 1895195e84767de180653914ce207245 # 4.0 Sound
        # Audio Formats
          - a50b8a0c62274a7c38b09a9619ba9d86 # AAC
        assign_scores_to:
          - name: 1080p
            score: 5
          - name: 2160p
            score: 5
          - name: 2160p Only
            score: 5

      - trash_ids:
        # [No Category]
          - 4a20cfb76b5f92a8ca22b894b32e71be # Multi-Episode
        # Miscellaneous
          - 7ba05c6e0e14e793538174c679126996 # MULTi
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        # Language profiles
          - 69aa1e159f97d860440b04cd6d590c4f # Language: Not English
        assign_scores_to:
          - name: 1080p
            score: -10
          - name: 2160p
            score: -10
          - name: 2160p Only
            score: -10
