sonarr:
  unlimited_sonarr:
    base_url: http://unlimited_sonarr:8989
    api_key: arr_api_key
            
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Media Naming Configuration
    media_naming:
      series: plex-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      
      # Choose between the standard or alternative quality profile setup (choose one only)
      # - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p

      # Choose between the standard or alternative quality profile setup (choose one only)
      # - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-quality-profile-web-2160p-alternative
      - template: sonarr-v4-custom-formats-web-2160p

      # Comment out any of the following includes to disable them
      #- template: sonarr-quality-definition-anime
      #- template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    quality_profiles:
      - name: Remux-1080p - Anime
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEBDL-1080p
          until_score: 10000
        min_format_score: 100
        score_set: anime-sonarr
        quality_sort: top
        qualities:
          - name: WEBDL-1080p
          - name: RIP-1080p
            qualities:
              - Bluray-1080p
              - WEBRip-1080p
              - HDTV-1080p
          - name: Bluray-1080p Remux
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
              - HDTV-720p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV

    custom_formats:
      - trash_ids:
        # Optional
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
        # [No Category]
          - 5d9fd1b1e06cd8a475462f40214b7df6 # FLUX
          - 4a20cfb76b5f92a8ca22b894b32e71be # Multi-Episode
        # Language profiles
          - ae575f95ab639ba5d15f663bf019e3e8 # Language: Not Original
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

      - trash_ids:
        # [No Category]
          - e0c1a67f23908a55b6ae9834e8ed6727 # Single Episode
        assign_scores_to:
          - name: WEB-1080p
            score: 10
          - name: WEB-2160p
            score: 10

      - trash_ids:
        # Language profiles
          - 69aa1e159f97d860440b04cd6d590c4f # Language: Not English
        # Miscellaneous
          - 7ba05c6e0e14e793538174c679126996 # MULTi
        # [No Category]
          - 4a20cfb76b5f92a8ca22b894b32e71be # Multi-Episode
        assign_scores_to:
          - name: WEB-1080p
            score: -10
          - name: WEB-2160p
            score: -10

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-1080p
            score: 0
          - name: WEB-2160p
            score: 0

      # HDR Formats
      - trash_ids:
          # Unified HDR
          - 505d871304820ba7106b693be6fe4a9e # HDR
          
          # Comment out the next line if you and all of your users' setups are fully DV compatible
          - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)

          # HDR10+ Boost - Uncomment the HDR10+ Boost line if you want to prefer HDR10+ releases
          # DV Boost - Uncomment the DV Boost line if you want to prefer DV releases
          # Uncomment both lines if you want to prefer both (DV HDR10+)
          - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost
          - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          # - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p

      #sonarr-v4-anime
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 25 # Adjust scoring as desired

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10 # Adjust scoring as desired

      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 25 # Adjust scoring as desired
